[env:iq200-radio]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 460800

board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=2
    -DBOARD_HAS_PSRAM
    -DIQ200_VERSION=\"9.9_ALPHA7_13_WEBRADIO_WEB_PLAYER\"

lib_deps =
    lovyan03/LovyanGFX@1.1.16
    https://github.com/mackron/dr_libs.git
    esphome/ESP32-audioI2S@2.0.7

lib_ldf_mode = chain
lib_compat_mode = soft
